### ISSUE TITLE
Where is python API?

### ISSUE THREAD

**Issue by tensor8** [cboulay/PSMoveService#466]
How do I get this working from python?

I've built this on OS X using xcode, and the build succeeded.

Here's what's in the build folder:
.
├── CMakeCache.txt
├── CMakeFiles
├── CMakeScripts
├── PSMoveService.build
├── PSMoveService.xcodeproj
├── cmake_install.cmake
└── src

What do I do next?

**Comment by tensor8** [comment]
OK, I found a `setup.py` in the examples folder.

`pip install -e .` throws an error, though:

> Obtaining file:///Users/user/code/grasp/PSMoveService/misc/python
    Complete output from command python setup.py egg_info:
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    KeyError: 'PYTHONPATH'
    Traceback (most recent call last):
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/cparser.py", line 269, in _parse
        ast = _get_parser().parse(csource)
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/c_parser.py", line 151, in parse
        debug=debuglevel)
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1181, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/c_parser.py", line 1721, in p_error
        column=self.clex.find_tok_column(p)))
      File "/Users/user/anaconda/lib/python3.6/site-packages/pycparser/plyparser.py", line 55, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: :151:5: before: PSMVector3f

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/user/code/grasp/PSMoveService/misc/python/setup.py", line 102, in <module>
        entry_points={},
      File "/Users/user/anaconda/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in __init__
        _Distribution.__init__(self, attrs)
      File "/Users/user/anaconda/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 471, in finalize_options
        ep.load()(self, ep.name, value)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "_cffi_build/psmove_cffi.py", line 73, in <module>
        ffi.cdef(get_cleaned_header())
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/api.py", line 106, in cdef
        self._cdef(csource, override=override, packed=packed)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/api.py", line 120, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/cparser.py", line 308, in parse
        self._internal_parse(csource)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/cparser.py", line 313, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/cparser.py", line 271, in _parse
        self.convert_pycparser_error(e, csource)
      File "/Users/user/anaconda/lib/python3.6/site-packages/cffi/cparser.py", line 300, in convert_pycparser_error
        raise CDefError(msg)
    cffi.error.CDefError: cannot parse "PSMVector3f LinearVelocityCmPerSec;"
    :151:5: before: PSMVector3f

**Comment by HipsterSloth** [comment]
Unfortunately I think the python API has rotted a bit since I did the last major C-API refactor. @cboulay did the main chunk of work to on getting the python wrapper in place. He might have some suggestions about how to proceed. Alternatively if you don't mind investigating the python wrapper code I'd appreciate the help. I don't have much time to look into this particular issue at the moment.

**Comment by tensor8** [comment]
Thanks, no problem!

**Comment by cboulay** [comment]
It's almost certainly that the [`get_cleaned_header` function](https://github.com/cboulay/PSMoveService/blob/master/misc/python/_cffi_build/psmove_cffi.py#L46-L62) needs to be updated to do a better job of parsing the header. If you are able, then please go ahead and rewrite that entire function. If you're good with regex than you can do a much better job than what's already there.

**Comment by cboulay** [comment]
If you ended up fixing the python wrapper then please submit a pull request.
Feel free to re-open the issue if you need to discuss this further.
